package com.glooory.flatreader.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.glooory.flatreader.entity.gank.GankBean;
import com.glooory.flatreader.entity.ithome.ITHomeItemBean;
import com.glooory.flatreader.entity.ribao.RibaoStoryBean;

import com.glooory.flatreader.greendao.GankBeanDao;
import com.glooory.flatreader.greendao.ITHomeItemBeanDao;
import com.glooory.flatreader.greendao.RibaoStoryBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gankBeanDaoConfig;
    private final DaoConfig iTHomeItemBeanDaoConfig;
    private final DaoConfig ribaoStoryBeanDaoConfig;

    private final GankBeanDao gankBeanDao;
    private final ITHomeItemBeanDao iTHomeItemBeanDao;
    private final RibaoStoryBeanDao ribaoStoryBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gankBeanDaoConfig = daoConfigMap.get(GankBeanDao.class).clone();
        gankBeanDaoConfig.initIdentityScope(type);

        iTHomeItemBeanDaoConfig = daoConfigMap.get(ITHomeItemBeanDao.class).clone();
        iTHomeItemBeanDaoConfig.initIdentityScope(type);

        ribaoStoryBeanDaoConfig = daoConfigMap.get(RibaoStoryBeanDao.class).clone();
        ribaoStoryBeanDaoConfig.initIdentityScope(type);

        gankBeanDao = new GankBeanDao(gankBeanDaoConfig, this);
        iTHomeItemBeanDao = new ITHomeItemBeanDao(iTHomeItemBeanDaoConfig, this);
        ribaoStoryBeanDao = new RibaoStoryBeanDao(ribaoStoryBeanDaoConfig, this);

        registerDao(GankBean.class, gankBeanDao);
        registerDao(ITHomeItemBean.class, iTHomeItemBeanDao);
        registerDao(RibaoStoryBean.class, ribaoStoryBeanDao);
    }
    
    public void clear() {
        gankBeanDaoConfig.clearIdentityScope();
        iTHomeItemBeanDaoConfig.clearIdentityScope();
        ribaoStoryBeanDaoConfig.clearIdentityScope();
    }

    public GankBeanDao getGankBeanDao() {
        return gankBeanDao;
    }

    public ITHomeItemBeanDao getITHomeItemBeanDao() {
        return iTHomeItemBeanDao;
    }

    public RibaoStoryBeanDao getRibaoStoryBeanDao() {
        return ribaoStoryBeanDao;
    }

}
