package com.glooory.flatreader.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.glooory.flatreader.entity.ithome.ITHomeItemBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ithome".
*/
public class ITHomeItemBeanDao extends AbstractDao<ITHomeItemBean, Long> {

    public static final String TABLENAME = "ithome";

    /**
     * Properties of entity ITHomeItemBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property IdPrimary = new Property(0, Long.class, "idPrimary", true, "_id");
        public final static Property Newsid = new Property(1, String.class, "newsid", false, "NEWS_ID");
    }


    public ITHomeItemBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ITHomeItemBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ithome\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: idPrimary
                "\"NEWS_ID\" TEXT UNIQUE );"); // 1: newsid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ithome\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ITHomeItemBean entity) {
        stmt.clearBindings();
 
        Long idPrimary = entity.getIdPrimary();
        if (idPrimary != null) {
            stmt.bindLong(1, idPrimary);
        }
 
        String newsid = entity.getNewsid();
        if (newsid != null) {
            stmt.bindString(2, newsid);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ITHomeItemBean entity) {
        stmt.clearBindings();
 
        Long idPrimary = entity.getIdPrimary();
        if (idPrimary != null) {
            stmt.bindLong(1, idPrimary);
        }
 
        String newsid = entity.getNewsid();
        if (newsid != null) {
            stmt.bindString(2, newsid);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ITHomeItemBean readEntity(Cursor cursor, int offset) {
        ITHomeItemBean entity = new ITHomeItemBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // idPrimary
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // newsid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ITHomeItemBean entity, int offset) {
        entity.setIdPrimary(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNewsid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ITHomeItemBean entity, long rowId) {
        entity.setIdPrimary(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ITHomeItemBean entity) {
        if(entity != null) {
            return entity.getIdPrimary();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ITHomeItemBean entity) {
        return entity.getIdPrimary() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
