package com.glooory.flatreader.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.glooory.flatreader.entity.ribao.RibaoStoryBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ribao".
*/
public class RibaoStoryBeanDao extends AbstractDao<RibaoStoryBean, Long> {

    public static final String TABLENAME = "ribao";

    /**
     * Properties of entity RibaoStoryBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property IdPrimary = new Property(0, Long.class, "idPrimary", true, "_id");
        public final static Property Id = new Property(1, String.class, "id", false, "NEWS_ID");
    }


    public RibaoStoryBeanDao(DaoConfig config) {
        super(config);
    }
    
    public RibaoStoryBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ribao\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: idPrimary
                "\"NEWS_ID\" TEXT UNIQUE );"); // 1: id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ribao\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RibaoStoryBean entity) {
        stmt.clearBindings();
 
        Long idPrimary = entity.getIdPrimary();
        if (idPrimary != null) {
            stmt.bindLong(1, idPrimary);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RibaoStoryBean entity) {
        stmt.clearBindings();
 
        Long idPrimary = entity.getIdPrimary();
        if (idPrimary != null) {
            stmt.bindLong(1, idPrimary);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RibaoStoryBean readEntity(Cursor cursor, int offset) {
        RibaoStoryBean entity = new RibaoStoryBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // idPrimary
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RibaoStoryBean entity, int offset) {
        entity.setIdPrimary(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RibaoStoryBean entity, long rowId) {
        entity.setIdPrimary(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RibaoStoryBean entity) {
        if(entity != null) {
            return entity.getIdPrimary();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RibaoStoryBean entity) {
        return entity.getIdPrimary() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
